### ISSUE TITLE
ImportError: cannot import name 'add_all_plugin_dirs' from 'ansible.plugins.loader' 

### ISSUE THREAD

**Issue by ianw** [ansible/ansible-lint#1091]
##### Summary
I am seeing with <= 4.3.6 the following

```
Traceback (most recent call last):
  File "/home/iwienand/programs/openstack-infra/project-config/.tox/linters/bin/ansible-lint", line 5, in <module>
    from ansiblelint.__main__ import main
  File "/home/iwienand/programs/openstack-infra/project-config/.tox/linters/lib/python3.8/site-packages/ansiblelint/__init__.py", line 22, in <module>
    from ansiblelint.rules import AnsibleLintRule
  File "/home/iwienand/programs/openstack-infra/project-config/.tox/linters/lib/python3.8/site-packages/ansiblelint/rules/__init__.py", line 12, in <module>
    import ansiblelint.utils
  File "/home/iwienand/programs/openstack-infra/project-config/.tox/linters/lib/python3.8/site-packages/ansiblelint/utils.py", line 43, in <module>
    from ansible.plugins.loader import add_all_plugin_dirs
ImportError: cannot import name 'add_all_plugin_dirs' from 'ansible.plugins.loader' (/home/iwienand/programs/openstack-infra/project-config/.tox/linters/lib/python3.8/site-packages/ansible/plugins/loader.py)
```

also in CI, e.g. https://zuul.opendev.org/t/openstack/build/7d4cda4dbe224d42a4c7e188ec3472c5/log/job-output.txt

##### Issue Type

- Bug Report

**Comment by ianw** [comment]
Sorry, I missed that this comes from ansible.plugins.  51696b5a7192b4f979be437ed10a97617ed0bae0 added this

setup.cfg defines ```ansible >= 2.8``` but our tox is setting things to 2.7 for some reason

**Comment by felixfontein** [comment]
Yep sorry, 2.7 is no longer supported. (And I only made sure it works with 2.8 and newer in that commit.)

Also please note that 2.7 is EOL (https://docs.ansible.com/ansible/devel/reference_appendices/release_and_maintenance.html#ansible-release-cycle).

**Comment by ssbarnea** [comment]
If anyone wants to add an extra check in the linter that assures it does not start with incompatible Ansible version, i will be happy to review it, especially as current version of pip allows for cases where incompatible dependencies are installed.
